apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modrena
  name: modrena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modrena
  template:
    metadata:
      labels:
        app: modrena
    spec:
      containers:
      - image: abdofadl/modrena:v${BUILD_NUMBER}
        name: modrena
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}