apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice2
  name: myservice2
spec:
  ports:
  - name: modrenaport
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: modrena
  type: NodePort
status:
  loadBalancer: {}